[package]
name = "risk5"
version = "0.1.0"
authors = ["Shane Gibbs <shane@hands.net.nz>"]

[dependencies]

elf = "0.0.10"
# log = { version = "0.4", features = ["max_level_trace", "release_max_level_warn"] }
log = { version = "0.4", features = ["max_level_trace", "release_max_level_trace"] }
pretty_env_logger = "0.2"
# wasm-bindgen = "0.2"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[build-dependencies]
regex = "1"

[[bin]]
name = "risk5"
path = "bin/risk5.rs"

[[bin]]
name = "logrunner"
path = "bin/logrunner.rs"

# [[bin]]
# name = "u1"
# path = "bin/u1.rs"

# [[bin]]
# name = "u2"
# path = "bin/u2.rs"

[profile.release]
panic = "abort"
