[package]
name = "derive_insn"
version = "0.1.0"
authors = ["Shane Gibbs <shane@hands.net.nz>"]

[lib]
proc-macro = true

[dependencies]
syn = "0.15"
quote = "0.6"
proc-macro2 = "0.4"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_trace"] }
